tinyMCE.addI18n('en.manual_dlg',{
	title : 'Quick manual',
	save : 'Save',
	empty : 'New empty page',
	printx : 'Print',
	preview : 'Preview the endresult',
	searchx : 'Search',
	replacex : 'Find and replace',
	spellcheck : 'Spellchecker',
	cut : 'Cut',
	paste : 'Paste',
	paste_plain : 'Paste as plain text',
	paste_word : 'Paste from Word',
	clean : 'Clean code',
	undo : 'Undo',
	redo : 'Redo',
	hyperlink : 'Insert or edit hyperlink',
	hyperlink_remove : 'Delete hyperlink',
	ank : 'Insert or edit an anchor',
	table : 'Insert table',
	table_row : 'Table row properties',
	table_cell : 'Table cell properties',
	table_insert_row : 'Insert table row before',
	table_insert_row2 : 'Insert table row after',
	table_delete_row : 'Delete table row',
	table_insert_column : 'Insert table column left',
	table_insert_column2 : 'Insert table column right',
	table_delete_column : 'Delete table column',
	table_split : 'Split table cells',
	table_merge : 'Merge table cells',
	manual : 'Show the quick manual',
	boldx : 'Bold',
	italic : 'Italic',
	underline : 'Underline',
	left : 'Align left',
	center : 'Align center',
	right : 'Align right',
	align_full : 'Align full',
	ul : 'Create unordered list',
	ol : 'Create orderdered list',
	outdent : 'Outdent',
	indent : 'Indent',
	hr : 'Insert horizontal rule (line)',
	formatting : 'Remove formatting',
	guidlines : 'Show guidlines',
	special : 'Insert Symbol',
	media : 'Insert or edit media',
	ibrowser : 'Upload and/or insert image',
	image : 'Edit image',
	dms : 'Insert files from DMS',
	abbr : 'Create abbreviation',
	dfn : 'Create definition',
	form : 'Insert formfields and labels',
	html : 'View and edit HTML source code'
});
