tinyMCE.addI18n('nl.manual_dlg',{
	title : 'Beknopte Gebruikershandleiding',
	save : 'Opslaan',
	empty : 'Nieuwe lege pagina',
	printx : 'Printen',
	preview : 'Eindresultaat voorbeeld',
	searchx : 'Zoeken',
	replacex : 'Zoeken en vervangen',
	spellcheck : 'Spellingscontrole',
	cut : 'Knippen',
	paste : 'Plakken',
	paste_plain : 'Plakken als platte tekst',
	paste_word : 'Plakken vanuit Word',
	clean : 'Code opruimen',
	undo : 'Ongedaan maken',
	redo : 'Opnieuw uitvoeren',
	hyperlink : 'Link invoegen of bewerken',
	hyperlink_remove : 'Link verwijderen',
	ank : 'Anker invoegen of bewerken',
	table : 'Tabel invoegen',
	table_row : 'Tabel rij-eigenschappen',
	table_cell : 'Tabel cell-eigenschappen',
	table_insert_row : 'Tabel-rij boven invoegen',
	table_insert_row2 : 'Tabel-rij onder invoegen',
	table_delete_row : 'Tabel-rij verwijderen',
	table_insert_column : 'Tabel-kolom links invoegen',
	table_insert_column2 : 'Tabel-kolom rechts inveogen',
	table_delete_column : 'Tabel-kolom verwijderen',
	table_split : 'Tabel-cellen splitsen',
	table_merge : 'Tabel-cellen samenvoegen',
	manual : 'Beknopte gebruikershandleiding weergeven',
	boldx : 'Vetgedrukt',
	italic : 'Cursief',
	underline : 'Onderstrepen',
	left : 'Links uitlijnen',
	center : 'Centreren',
	right : 'Rechts uitlijnen',
	align_full : 'Uitvullen',
	ul : 'Lijst met opsommingen maken',
	ol : 'Genummerde lijst maken',
	outdent : 'Inspringing verkleinen',
	indent : 'Inspringing vergroten',
	hr : 'Horizontale lijn invoegen',
	formatting : 'Opmaak opruimen',
	guidlines : 'Hulplijnen weergeven',
	special : 'Speciale karakters invoegen',
	media : 'Media invoegen of bewerken',
	ibrowser : 'Afbeeldingen uploaden en/of invoegen',
	image : 'Afbeeldingen bewerken',
	dms : 'Bestanden uit het DMS invoegen',
	abbr : 'Afkorting aanmaken',
	dfn : 'Definitie aanmaken',
	form : 'Formuliervelden en labels invoegen',
	html : 'HTML broncode bekijken en/of wijzigen'
});
